services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DirkPersky\Theme\:
    resource: '../Classes/*'
    exclude:  '../Classes/Domain/Model/*'

  DirkPersky\Theme\EventListener\AdditionalPropertiesForSearch:
    tags:
      - name: event.listener
        identifier: 'myAdditionalPropertiesForSearch'
        event: Brotkrueml\Schema\Event\RegisterAdditionalTypePropertiesEvent
